theme: jekyll-theme-leap-day
title: The quiz - Are you using the data science tool kit for open science?
# logo: /assets/img/logo.png
description: Evaluate your use of the data science tool kit
# show_downloads: true
# google_analytics: