theme: jekyll-theme-leap-day
title: The quiz - Are you using the data science tool kit for open science?
# logo: /assets/img/logo.png
description: How we marked the quiz and additional resources
# show_downloads: true
# google_analytics: